kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: get-messages
  labels:
    name: message-api
spec:
  host: modern-ui.apps.openshift.rhcasalab.com
  path: /api/messages
  to:
    kind: Service
    name: message-api
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None


